name: Build and Publish Container

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF_NAME#v}
            docker build \
              -t ghcr.io/utedass/zebra-webb:latest \
              -t ghcr.io/utedass/zebra-webb:$VERSION \
              .
          else
            docker build \
              -t ghcr.io/utedass/zebra-webb:latest \
              .
          fi

      - name: Push image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF_NAME#v}
            docker push ghcr.io/utedass/zebra-webb:$VERSION
          fi
          docker push ghcr.io/utedass/zebra-webb:latest
