name: Build and Publish Container

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: action/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Utedass
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/utedass/zebra-webb:latest .

      - name: Push image
        run: |
          docker push ghcr.io/utedass/zebra-webb:latest
